# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `abstract_type` gem.
# Please instead update this file by running `bin/tapioca gem abstract_type`.

module AbstractType
  mixes_in_class_methods ::AbstractType::AbstractMethodDeclarations

  class << self
    private

    def create_new_method(abstract_class); end
    def included(descendant); end
  end
end

module AbstractType::AbstractMethodDeclarations
  def abstract_method(*names); end
  def abstract_singleton_method(*names); end

  private

  def create_abstract_instance_method(name); end
  def create_abstract_singleton_method(name); end
end

AbstractType::VERSION = T.let(T.unsafe(nil), String)
