# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `adamantium` gem.
# Please instead update this file by running `bin/tapioca gem adamantium`.

module Adamantium
  include ::Memoizable

  mixes_in_class_methods ::Memoizable::ModuleMethods
  mixes_in_class_methods ::Adamantium::ModuleMethods
  mixes_in_class_methods ::Adamantium::ClassMethods

  def dup; end

  protected

  def transform(&block); end
  def transform_unless(condition, &block); end

  private

  def __adamantium_dup__; end

  class << self
    private

    def included(descendant); end
  end
end

module Adamantium::ClassMethods
  def new(*_arg0); end
end

module Adamantium::Flat
  include ::Memoizable
  include ::Adamantium

  mixes_in_class_methods ::Memoizable::ModuleMethods
  mixes_in_class_methods ::Adamantium::ModuleMethods
  mixes_in_class_methods ::Adamantium::ClassMethods

  def freezer; end

  class << self
    private

    def included(descendant); end
  end
end

class Adamantium::Freezer
  class << self
    def get(name); end
    def parse(options); end

    private

    def call(object); end
    def freeze_value(value); end
  end
end

class Adamantium::Freezer::Deep < ::Adamantium::Freezer
  class << self
    def freeze(value); end
  end
end

class Adamantium::Freezer::Flat < ::Adamantium::Freezer
  class << self
    def freeze(value); end
  end
end

Adamantium::Freezer::Noop = T.let(T.unsafe(nil), Proc)
class Adamantium::Freezer::OptionError < ::RuntimeError; end
class Adamantium::Freezer::UnknownFreezerError < ::RuntimeError; end

module Adamantium::ModuleMethods
  def freezer; end
  def memoize(*methods); end

  private

  def included(descendant); end
  def memoize_method(method_name, freezer); end
end

module Adamantium::Mutable
  def freeze; end
  def frozen?; end
end

Adamantium::VERSION = T.let(T.unsafe(nil), String)
