# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `anima` gem.
# Please instead update this file by running `bin/tapioca gem anima`.

class Anima < ::Module
  include ::Equalizer::Methods
  include ::Adamantium::Flat
  include ::Adamantium
  include ::Memoizable::InstanceMethods
  include ::Memoizable
  extend ::Memoizable::ModuleMethods
  extend ::Adamantium::ModuleMethods
  extend ::Adamantium::ClassMethods
  extend ::Adamantium::Flat

  def initialize(*names); end

  def add(*names); end
  def attribute_names(&block); end
  def attributes; end
  def attributes_hash(object); end
  def initialize_instance(object, attribute_hash); end
  def remove(*names); end

  private

  def assert_known_attributes(klass, attribute_hash); end
  def included(descendant); end
  def new(attributes); end
end

class Anima::Attribute
  include ::Equalizer::Methods
  include ::Adamantium::Flat
  include ::Adamantium
  include ::Memoizable::InstanceMethods
  include ::Memoizable
  extend ::Memoizable::ModuleMethods
  extend ::Adamantium::ModuleMethods
  extend ::Adamantium::ClassMethods
  extend ::Adamantium::Flat

  def initialize(name); end

  def get(object); end
  def instance_variable_name; end
  def load(object, attributes); end
  def name; end
  def set(object, value); end
end

class Anima::Error < ::RuntimeError
  def initialize(klass, missing, unknown); end
end

Anima::Error::FORMAT = T.let(T.unsafe(nil), String)

module Anima::InstanceMethods
  def initialize(attributes); end

  def to_h; end
  def with(attributes); end
end
