# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `concord` gem.
# Please instead update this file by running `bin/tapioca gem concord`.

class Concord < ::Module
  include ::Equalizer::Methods
  include ::Adamantium::Flat
  include ::Adamantium
  include ::Memoizable::InstanceMethods
  include ::Memoizable
  extend ::Memoizable::ModuleMethods
  extend ::Adamantium::ModuleMethods
  extend ::Adamantium::ClassMethods
  extend ::Adamantium::Flat

  def initialize(*names); end

  def names; end

  private

  def define_equalizer; end
  def define_initialize; end
  def define_readers; end
  def included(descendant); end
  def instance_variable_names; end
end

Concord::MAX_NR_OF_OBJECTS = T.let(T.unsafe(nil), Integer)

class Concord::Public < ::Concord
  def included(descendant); end
end
