# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `mprelude` gem.
# Please instead update this file by running `bin/tapioca gem mprelude`.

module MPrelude; end

class MPrelude::Either
  include ::AbstractType
  include ::MPrelude::RequireBlock
  include ::Equalizer::Methods
  include ::Adamantium::Flat
  include ::Adamantium
  include ::Memoizable::InstanceMethods
  include ::Memoizable
  extend ::Memoizable::ModuleMethods
  extend ::Adamantium::ModuleMethods
  extend ::Adamantium::ClassMethods
  extend ::Adamantium::Flat
  extend ::AbstractType::AbstractMethodDeclarations

  def left?; end
  def right?; end

  class << self
    def new(*args, &block); end
    def wrap_error(*exceptions); end
  end
end

class MPrelude::Either::Left < ::MPrelude::Either
  def bind(&block); end
  def either(left, _right); end
  def fmap(&block); end
  def from_left; end
  def from_right; end
  def lmap; end
end

class MPrelude::Either::Right < ::MPrelude::Either
  def bind; end
  def either(_left, right); end
  def fmap; end
  def from_left; end
  def from_right; end
  def lmap(&block); end
end

class MPrelude::Maybe
  include ::AbstractType
  include ::MPrelude::RequireBlock
  include ::Adamantium::Flat
  include ::Adamantium
  include ::Memoizable::InstanceMethods
  include ::Memoizable
  extend ::Memoizable::ModuleMethods
  extend ::Adamantium::ModuleMethods
  extend ::Adamantium::ClassMethods
  extend ::Adamantium::Flat
  extend ::AbstractType::AbstractMethodDeclarations

  class << self
    def new(*args, &block); end
  end
end

class MPrelude::Maybe::Just < ::MPrelude::Maybe
  include ::Equalizer::Methods

  def bind; end
  def fmap; end
end

class MPrelude::Maybe::Nothing < ::MPrelude::Maybe
  def bind(&block); end
  def fmap(&block); end
  def new; end
end

module MPrelude::RequireBlock
  include ::AbstractType
  extend ::AbstractType::AbstractMethodDeclarations

  private

  def require_block; end

  class << self
    def new(*args, &block); end
  end
end
