# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `procto` gem.
# Please instead update this file by running `bin/tapioca gem procto`.

class Procto < ::Module
  def initialize(name); end

  private

  def included(host); end

  class << self
    def call(name = T.unsafe(nil)); end
  end
end

module Procto::ClassMethods
  def to_proc; end
end

Procto::DEFAULT_NAME = T.let(T.unsafe(nil), Symbol)
