# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rspock` gem.
# Please instead update this file by running `bin/tapioca gem rspock`.


# TODO: Give Credits to Rails, borrowed from ActiveSupport::Testing::Declarative
#
# source://rspock//lib/rspock/version.rb#1
module RSpock; end

# source://rspock//lib/rspock/ast/node.rb#5
module RSpock::AST; end

# source://rspock//lib/rspock/ast/node.rb#104
class RSpock::AST::BinaryStatementNode < ::RSpock::AST::Node
  # source://rspock//lib/rspock/ast/node.rb#107
  def lhs; end

  # source://rspock//lib/rspock/ast/node.rb#108
  def operator; end

  # source://rspock//lib/rspock/ast/node.rb#109
  def rhs; end
end

# source://rspock//lib/rspock/ast/node.rb#27
class RSpock::AST::BodyNode < ::RSpock::AST::Node; end

# source://rspock//lib/rspock/ast/node.rb#54
class RSpock::AST::CleanupNode < ::RSpock::AST::Node; end

# source://rspock//lib/rspock/ast/node.rb#31
class RSpock::AST::DefNode < ::RSpock::AST::Node
  # source://rspock//lib/rspock/ast/node.rb#35
  def args; end

  # source://rspock//lib/rspock/ast/node.rb#34
  def method_call; end
end

# source://rspock//lib/rspock/ast/node.rb#50
class RSpock::AST::ExpectNode < ::RSpock::AST::Node; end

# source://rspock//lib/rspock/ast/node.rb#38
class RSpock::AST::GivenNode < ::RSpock::AST::Node; end

# source://rspock//lib/rspock/ast/header_nodes_transformation.rb#6
class RSpock::AST::HeaderNodesTransformation < ::ASTTransform::AbstractTransformation
  # @return [HeaderNodesTransformation] a new instance of HeaderNodesTransformation
  #
  # source://rspock//lib/rspock/ast/header_nodes_transformation.rb#7
  def initialize(header); end

  # source://rspock//lib/rspock/ast/header_nodes_transformation.rb#17
  def on_send(node); end

  # source://rspock//lib/rspock/ast/header_nodes_transformation.rb#11
  def run(node); end

  private

  # @return [Boolean]
  #
  # source://rspock//lib/rspock/ast/header_nodes_transformation.rb#25
  def header_node?(node); end
end

# source://rspock//lib/rspock/ast/node.rb#92
class RSpock::AST::InteractionNode < ::RSpock::AST::Node
  # source://rspock//lib/rspock/ast/node.rb#99
  def args; end

  # source://rspock//lib/rspock/ast/node.rb#101
  def block_pass; end

  # source://rspock//lib/rspock/ast/node.rb#95
  def cardinality; end

  # source://rspock//lib/rspock/ast/node.rb#98
  def message; end

  # source://rspock//lib/rspock/ast/node.rb#97
  def message_sym; end

  # source://rspock//lib/rspock/ast/node.rb#100
  def outcome; end

  # source://rspock//lib/rspock/ast/node.rb#96
  def receiver; end
end

# Transforms an :rspock_interaction node into an assert_same assertion
# when a block_pass (&var) is present.
#
# Returns the node unchanged (passthrough) when no block_pass is present.
#
# source://rspock//lib/rspock/ast/interaction_to_block_identity_assertion_transformation.rb#11
class RSpock::AST::InteractionToBlockIdentityAssertionTransformation < ::ASTTransform::AbstractTransformation
  # @return [InteractionToBlockIdentityAssertionTransformation] a new instance of InteractionToBlockIdentityAssertionTransformation
  #
  # source://rspock//lib/rspock/ast/interaction_to_block_identity_assertion_transformation.rb#12
  def initialize(index = T.unsafe(nil)); end

  # source://rspock//lib/rspock/ast/interaction_to_block_identity_assertion_transformation.rb#16
  def run(interaction); end
end

# Transforms an :rspock_interaction node into Mocha mock setup code.
#
# Input:  s(:rspock_interaction, cardinality, receiver, sym, args, outcome, block_pass)
# Output: receiver.expects(:message).with(*args).times(n).returns(value)
#
# The outcome node type maps directly to the Mocha chain method:
#   :rspock_stub_returns -> .returns(value)
#   :rspock_stub_raises  -> .raises(exception_class, ...)
#
# When block_pass is present, wraps the expects chain with a BlockCapture.capture call.
#
# source://rspock//lib/rspock/ast/interaction_to_mocha_mock_transformation.rb#17
class RSpock::AST::InteractionToMochaMockTransformation < ::ASTTransform::AbstractTransformation
  # @return [InteractionToMochaMockTransformation] a new instance of InteractionToMochaMockTransformation
  #
  # source://rspock//lib/rspock/ast/interaction_to_mocha_mock_transformation.rb#23
  def initialize(index = T.unsafe(nil)); end

  # source://rspock//lib/rspock/ast/interaction_to_mocha_mock_transformation.rb#27
  def run(interaction); end

  private

  # @return [Boolean]
  #
  # source://rspock//lib/rspock/ast/interaction_to_mocha_mock_transformation.rb#108
  def any_matcher_node?(node); end

  # source://rspock//lib/rspock/ast/interaction_to_mocha_mock_transformation.rb#89
  def build_block_capture_setup(expects_node, receiver, message); end

  # source://rspock//lib/rspock/ast/interaction_to_mocha_mock_transformation.rb#44
  def build_cardinality(result, cardinality); end

  # source://rspock//lib/rspock/ast/interaction_to_mocha_mock_transformation.rb#75
  def build_erange(result, min_node, max_node); end

  # source://rspock//lib/rspock/ast/interaction_to_mocha_mock_transformation.rb#61
  def build_irange(result, min_node, max_node); end

  # source://rspock//lib/rspock/ast/interaction_to_mocha_mock_transformation.rb#104
  def chain_call(receiver_node, method_name, *arg_nodes); end
end

# source://rspock//lib/rspock/ast/interaction_to_mocha_mock_transformation.rb#18
RSpock::AST::InteractionToMochaMockTransformation::OUTCOME_METHODS = T.let(T.unsafe(nil), Hash)

# source://rspock//lib/rspock/ast/method_call_to_lvar_transformation.rb#6
class RSpock::AST::MethodCallToLVarTransformation < ::ASTTransform::AbstractTransformation
  # @return [MethodCallToLVarTransformation] a new instance of MethodCallToLVarTransformation
  #
  # source://rspock//lib/rspock/ast/method_call_to_lvar_transformation.rb#7
  def initialize(*method_symbols); end

  # @return [Boolean]
  #
  # source://rspock//lib/rspock/ast/method_call_to_lvar_transformation.rb#19
  def method_call_node?(node); end

  # source://rspock//lib/rspock/ast/method_call_to_lvar_transformation.rb#13
  def on_send(node); end
end

# source://rspock//lib/rspock/ast/node.rb#6
class RSpock::AST::Node < ::Parser::AST::Node
  class << self
    # source://rspock//lib/rspock/ast/node.rb#13
    def build(type, *children); end

    # source://rspock//lib/rspock/ast/node.rb#9
    def register(type); end
  end
end

# source://rspock//lib/rspock/ast/node.rb#7
RSpock::AST::Node::REGISTRY = T.let(T.unsafe(nil), Hash)

# source://rspock//lib/rspock/ast/node.rb#119
module RSpock::AST::NodeBuilder
  include ::ASTTransform::TransformationHelper
  include ::ASTTransform::TransformationHelper::Methods
  extend ::ASTTransform::TransformationHelper::Methods

  # source://rspock//lib/rspock/ast/node.rb#122
  def s(type, *children); end
end

# source://rspock//lib/rspock/ast/node.rb#73
class RSpock::AST::OutcomeNode < ::RSpock::AST::Node; end

# source://rspock//lib/rspock/ast/parser/block.rb#6
module RSpock::AST::Parser; end

# source://rspock//lib/rspock/ast/parser/block.rb#9
class RSpock::AST::Parser::Block
  include ::ASTTransform::TransformationHelper
  include ::ASTTransform::TransformationHelper::Methods
  include ::RSpock::AST::NodeBuilder

  # Constructs a new Block.
  #
  # @param node [Parser::AST::Node] The node associated to this Block.
  # @param type [Symbol] The Block type.
  # @return [Block] a new instance of Block
  #
  # source://rspock//lib/rspock/ast/parser/block.rb#16
  def initialize(type, node); end

  # Adds the given +child_node+ to this Block.
  #
  # @param child_node [Parser::AST::Node] The node to be added.
  #
  # source://rspock//lib/rspock/ast/parser/block.rb#27
  def <<(child_node); end

  # Whether this block can be the last block in a test method.
  #
  # @return [Boolean]
  #
  # source://rspock//lib/rspock/ast/parser/block.rb#44
  def can_end?; end

  # Whether this block can be the first block in a test method.
  #
  # @return [Boolean]
  #
  # source://rspock//lib/rspock/ast/parser/block.rb#39
  def can_start?; end

  # Retrieves the duped array of children AST nodes for this Block.
  #
  # @return [Array<Parser::AST::Node>] The children nodes.
  #
  # source://rspock//lib/rspock/ast/parser/block.rb#58
  def children; end

  # Returns the value of attribute node.
  #
  # source://rspock//lib/rspock/ast/parser/block.rb#22
  def node; end

  # Retrieves the Parser::Source::Range for this Block.
  #
  # @return [Parser::Source::Range] The range.
  #
  # source://rspock//lib/rspock/ast/parser/block.rb#34
  def range; end

  # Retrieves the error message for succession errors.
  #
  # @return [String] The error message.
  #
  # source://rspock//lib/rspock/ast/parser/block.rb#82
  def succession_error_msg; end

  # Retrieves the valid successors for this Block.
  #
  # @return [Array<Symbol>] This Block's successors.
  #
  # source://rspock//lib/rspock/ast/parser/block.rb#51
  def successors; end

  # Converts this Block into an RSpock node.
  #
  # @return [Parser::AST::Node] A node with type :rspock_<block_type>.
  #
  # source://rspock//lib/rspock/ast/parser/block.rb#65
  def to_rspock_node; end

  # Returns the value of attribute type.
  #
  # source://rspock//lib/rspock/ast/parser/block.rb#22
  def type; end

  # Checks whether or not the given +block+ is a valid successor for this Block.
  #
  # @param block [Block] The candidate successor.
  # @return [Boolean] True if the given block is a valid successor, false otherwise.
  #
  # source://rspock//lib/rspock/ast/parser/block.rb#75
  def valid_successor?(block); end
end

# source://rspock//lib/rspock/ast/parser/block.rb#7
class RSpock::AST::Parser::BlockError < ::StandardError; end

# source://rspock//lib/rspock/ast/parser/cleanup_block.rb#7
class RSpock::AST::Parser::CleanupBlock < ::RSpock::AST::Parser::Block
  # @return [CleanupBlock] a new instance of CleanupBlock
  #
  # source://rspock//lib/rspock/ast/parser/cleanup_block.rb#8
  def initialize(node); end

  # @return [Boolean]
  #
  # source://rspock//lib/rspock/ast/parser/cleanup_block.rb#12
  def can_end?; end

  # source://rspock//lib/rspock/ast/parser/cleanup_block.rb#16
  def successors; end
end

# source://rspock//lib/rspock/ast/parser/expect_block.rb#8
class RSpock::AST::Parser::ExpectBlock < ::RSpock::AST::Parser::Block
  # @return [ExpectBlock] a new instance of ExpectBlock
  #
  # source://rspock//lib/rspock/ast/parser/expect_block.rb#9
  def initialize(node); end

  # @return [Boolean]
  #
  # source://rspock//lib/rspock/ast/parser/expect_block.rb#17
  def can_end?; end

  # @return [Boolean]
  #
  # source://rspock//lib/rspock/ast/parser/expect_block.rb#13
  def can_start?; end

  # source://rspock//lib/rspock/ast/parser/expect_block.rb#21
  def successors; end

  # source://rspock//lib/rspock/ast/parser/expect_block.rb#25
  def to_rspock_node; end
end

# source://rspock//lib/rspock/ast/parser/given_block.rb#7
class RSpock::AST::Parser::GivenBlock < ::RSpock::AST::Parser::Block
  # @return [GivenBlock] a new instance of GivenBlock
  #
  # source://rspock//lib/rspock/ast/parser/given_block.rb#8
  def initialize(node); end

  # @return [Boolean]
  #
  # source://rspock//lib/rspock/ast/parser/given_block.rb#12
  def can_start?; end

  # source://rspock//lib/rspock/ast/parser/given_block.rb#16
  def successors; end
end

# Parses raw Ruby AST interaction nodes into structured :rspock_interaction nodes.
#
# Input:  1 * receiver.message("arg", &blk) >> "result"
# Output: s(:rspock_interaction, cardinality, receiver, sym, args, outcome, block_pass)
#
# :rspock_interaction children:
#   [0] cardinality  - e.g. s(:int, 1), s(:begin, s(:irange, ...)), s(:send, nil, :_)
#   [1] receiver     - e.g. s(:send, nil, :subscriber)
#   [2] message      - e.g. s(:sym, :receive)
#   [3] args         - nil if no args, s(:array, *arg_nodes) otherwise
#   [4] outcome      - nil if no >>, otherwise s(:rspock_stub_returns, value) or s(:rspock_stub_raises, *args)
#   [5] block_pass   - nil if no &, otherwise s(:block_pass, ...)
#
# source://rspock//lib/rspock/ast/parser/interaction_parser.rb#19
class RSpock::AST::Parser::InteractionParser
  include ::ASTTransform::TransformationHelper
  include ::ASTTransform::TransformationHelper::Methods
  include ::RSpock::AST::NodeBuilder

  # @return [Boolean]
  #
  # source://rspock//lib/rspock/ast/parser/interaction_parser.rb#26
  def interaction_node?(node); end

  # source://rspock//lib/rspock/ast/parser/interaction_parser.rb#34
  def parse(node); end

  private

  # source://rspock//lib/rspock/ast/parser/interaction_parser.rb#64
  def parse_outcome(node); end

  # source://rspock//lib/rspock/ast/parser/interaction_parser.rb#102
  def parse_rhs(node); end

  # @raise [InteractionError]
  #
  # source://rspock//lib/rspock/ast/parser/interaction_parser.rb#132
  def raise_cardinality_error(node, msg_prefix: T.unsafe(nil), msg_suffix: T.unsafe(nil)); end

  # source://rspock//lib/rspock/ast/parser/interaction_parser.rb#128
  def range(node); end

  # @return [Boolean]
  #
  # source://rspock//lib/rspock/ast/parser/interaction_parser.rb#60
  def return_value_node?(node); end

  # source://rspock//lib/rspock/ast/parser/interaction_parser.rb#72
  def validate_cardinality(node); end
end

# source://rspock//lib/rspock/ast/parser/interaction_parser.rb#24
RSpock::AST::Parser::InteractionParser::ALLOWED_CARDINALITY_NODES = T.let(T.unsafe(nil), Array)

# source://rspock//lib/rspock/ast/parser/interaction_parser.rb#22
class RSpock::AST::Parser::InteractionParser::InteractionError < ::RuntimeError; end

# Classifies raw Ruby AST statements into RSpock node types for Then/Expect blocks.
#
# - Assignments pass through as raw AST (no wrapping).
# - Binary operators (==, !=, =~, etc.) become :rspock_binary_statement nodes.
# - Everything else becomes :rspock_statement nodes with the original source text captured.
#
# source://rspock//lib/rspock/ast/parser/statement_parser.rb#12
class RSpock::AST::Parser::StatementParser
  include ::ASTTransform::TransformationHelper
  include ::ASTTransform::TransformationHelper::Methods
  include ::RSpock::AST::NodeBuilder

  # source://rspock//lib/rspock/ast/parser/statement_parser.rb#18
  def parse(node); end

  private

  # @return [Boolean]
  #
  # source://rspock//lib/rspock/ast/parser/statement_parser.rb#36
  def assigned_raises?(node); end

  # @return [Boolean]
  #
  # source://rspock//lib/rspock/ast/parser/statement_parser.rb#54
  def assignment?(node); end

  # @return [Boolean]
  #
  # source://rspock//lib/rspock/ast/parser/statement_parser.rb#58
  def binary_statement?(node); end

  # source://rspock//lib/rspock/ast/parser/statement_parser.rb#64
  def build_binary_statement(node); end

  # source://rspock//lib/rspock/ast/parser/statement_parser.rb#43
  def build_raises(node); end

  # source://rspock//lib/rspock/ast/parser/statement_parser.rb#68
  def build_statement(node); end

  # @return [Boolean]
  #
  # source://rspock//lib/rspock/ast/parser/statement_parser.rb#32
  def direct_raises?(node); end

  # @return [Boolean]
  #
  # source://rspock//lib/rspock/ast/parser/statement_parser.rb#28
  def raises_condition?(node); end
end

# source://rspock//lib/rspock/ast/parser/statement_parser.rb#16
RSpock::AST::Parser::StatementParser::ASSIGNMENT_TYPES = T.let(T.unsafe(nil), Array)

# source://rspock//lib/rspock/ast/parser/statement_parser.rb#15
RSpock::AST::Parser::StatementParser::BINARY_OPERATORS = T.let(T.unsafe(nil), Array)

# Parses a Ruby test method AST node into a self-contained RSpock AST.
#
# Input:  s(:block, s(:send, nil, :test, ...), s(:args), s(:begin, ...))
# Output: s(:rspock_test,
#           s(:rspock_def, method_call_node, args_node),
#           s(:rspock_body, s(:rspock_given, ...), s(:rspock_when, ...), ...),
#           s(:rspock_where, ...))   # optional
#
# source://rspock//lib/rspock/ast/parser/test_method_parser.rb#14
class RSpock::AST::Parser::TestMethodParser
  include ::ASTTransform::TransformationHelper
  include ::ASTTransform::TransformationHelper::Methods
  include ::RSpock::AST::NodeBuilder

  # @return [TestMethodParser] a new instance of TestMethodParser
  #
  # source://rspock//lib/rspock/ast/parser/test_method_parser.rb#17
  def initialize(block_registry, strict: T.unsafe(nil)); end

  # Parses a Ruby test method AST into an RSpock AST (TestNode).
  # Returns nil when non-strict and no RSpock blocks are found.
  #
  # source://rspock//lib/rspock/ast/parser/test_method_parser.rb#24
  def parse(node); end

  private

  # source://rspock//lib/rspock/ast/parser/test_method_parser.rb#87
  def build_rspock_ast(node, blocks); end

  # source://rspock//lib/rspock/ast/parser/test_method_parser.rb#56
  def parse_block(node); end

  # source://rspock//lib/rspock/ast/parser/test_method_parser.rb#38
  def parse_blocks(node); end

  # source://rspock//lib/rspock/ast/parser/test_method_parser.rb#81
  def test_method_nodes(node); end

  # source://rspock//lib/rspock/ast/parser/test_method_parser.rb#71
  def validate_blocks(blocks, node); end

  # source://rspock//lib/rspock/ast/parser/test_method_parser.rb#62
  def validate_succession(blocks, new_block); end
end

# source://rspock//lib/rspock/ast/parser/then_block.rb#9
class RSpock::AST::Parser::ThenBlock < ::RSpock::AST::Parser::Block
  # @return [ThenBlock] a new instance of ThenBlock
  #
  # source://rspock//lib/rspock/ast/parser/then_block.rb#10
  def initialize(node); end

  # @return [Boolean]
  #
  # source://rspock//lib/rspock/ast/parser/then_block.rb#14
  def can_end?; end

  # source://rspock//lib/rspock/ast/parser/then_block.rb#18
  def successors; end

  # source://rspock//lib/rspock/ast/parser/then_block.rb#22
  def to_rspock_node; end
end

# source://rspock//lib/rspock/ast/parser/when_block.rb#7
class RSpock::AST::Parser::WhenBlock < ::RSpock::AST::Parser::Block
  # @return [WhenBlock] a new instance of WhenBlock
  #
  # source://rspock//lib/rspock/ast/parser/when_block.rb#8
  def initialize(node); end

  # @return [Boolean]
  #
  # source://rspock//lib/rspock/ast/parser/when_block.rb#12
  def can_start?; end

  # source://rspock//lib/rspock/ast/parser/when_block.rb#16
  def successors; end
end

# source://rspock//lib/rspock/ast/parser/where_block.rb#7
class RSpock::AST::Parser::WhereBlock < ::RSpock::AST::Parser::Block
  # @return [WhereBlock] a new instance of WhereBlock
  #
  # source://rspock//lib/rspock/ast/parser/where_block.rb#10
  def initialize(node); end

  # @return [Boolean]
  #
  # source://rspock//lib/rspock/ast/parser/where_block.rb#28
  def can_end?; end

  # source://rspock//lib/rspock/ast/parser/where_block.rb#18
  def data; end

  # source://rspock//lib/rspock/ast/parser/where_block.rb#14
  def header; end

  # source://rspock//lib/rspock/ast/parser/where_block.rb#22
  def to_rspock_node; end

  private

  # @return [Boolean]
  #
  # source://rspock//lib/rspock/ast/parser/where_block.rb#74
  def data_pipe_node?(node, data); end

  # @return [Boolean]
  #
  # source://rspock//lib/rspock/ast/parser/where_block.rb#40
  def header_pipe_node?(node, header); end

  # source://rspock//lib/rspock/ast/parser/where_block.rb#65
  def parse_data; end

  # source://rspock//lib/rspock/ast/parser/where_block.rb#34
  def parse_header; end

  # @return [Boolean]
  #
  # source://rspock//lib/rspock/ast/parser/where_block.rb#87
  def terminal_data_node?(node, data); end

  # @raise [MalformedError]
  # @return [Boolean]
  #
  # source://rspock//lib/rspock/ast/parser/where_block.rb#50
  def terminal_header_node?(node, header); end
end

# source://rspock//lib/rspock/ast/parser/where_block.rb#8
class RSpock::AST::Parser::WhereBlock::MalformedError < ::StandardError; end

# source://rspock//lib/rspock/ast/node.rb#84
class RSpock::AST::RaisesNode < ::RSpock::AST::Node
  # source://rspock//lib/rspock/ast/node.rb#89
  def capture_name; end

  # source://rspock//lib/rspock/ast/node.rb#88
  def capture_var; end

  # source://rspock//lib/rspock/ast/node.rb#87
  def exception_class; end
end

# source://rspock//lib/rspock/ast/node.rb#112
class RSpock::AST::StatementNode < ::RSpock::AST::Node
  # source://rspock//lib/rspock/ast/node.rb#115
  def expression; end

  # source://rspock//lib/rspock/ast/node.rb#116
  def source; end
end

# Transforms :rspock_binary_statement and :rspock_statement nodes into Minitest assertion calls.
#
# Binary statements dispatch to specialized assertions (assert_equal, assert_match, assert_operator).
# General statements use assert_equal(true/false, expr, source_message) with negation detection.
#
# source://rspock//lib/rspock/ast/statement_to_assertion_transformation.rb#10
class RSpock::AST::StatementToAssertionTransformation
  include ::ASTTransform::TransformationHelper
  include ::ASTTransform::TransformationHelper::Methods
  include ::RSpock::AST::NodeBuilder

  # source://rspock//lib/rspock/ast/statement_to_assertion_transformation.rb#22
  def run(node); end

  private

  # @return [Boolean]
  #
  # source://rspock//lib/rspock/ast/statement_to_assertion_transformation.rb#63
  def negated?(node); end

  # source://rspock//lib/rspock/ast/statement_to_assertion_transformation.rb#35
  def transform_binary_statement(node); end

  # source://rspock//lib/rspock/ast/statement_to_assertion_transformation.rb#49
  def transform_statement(node); end
end

# source://rspock//lib/rspock/ast/statement_to_assertion_transformation.rb#13
RSpock::AST::StatementToAssertionTransformation::BINARY_DISPATCH = T.let(T.unsafe(nil), Hash)

# source://rspock//lib/rspock/ast/statement_to_assertion_transformation.rb#20
RSpock::AST::StatementToAssertionTransformation::OPERATOR_ASSERTIONS = T.let(T.unsafe(nil), Array)

# source://rspock//lib/rspock/ast/node.rb#80
class RSpock::AST::StubRaisesNode < ::RSpock::AST::OutcomeNode; end

# source://rspock//lib/rspock/ast/node.rb#76
class RSpock::AST::StubReturnsNode < ::RSpock::AST::OutcomeNode; end

# source://rspock//lib/rspock/ast/test_method_def_transformation.rb#7
class RSpock::AST::TestMethodDefTransformation < ::ASTTransform::AbstractTransformation
  # source://rspock//lib/rspock/ast/test_method_def_transformation.rb#29
  def on_dstr(node); end

  # source://rspock//lib/rspock/ast/test_method_def_transformation.rb#24
  def on_str(node); end

  # source://rspock//lib/rspock/ast/test_method_def_transformation.rb#18
  def run(node); end
end

# source://rspock//lib/rspock/ast/test_method_def_transformation.rb#11
RSpock::AST::TestMethodDefTransformation::LINE_NUMBER_AST = T.let(T.unsafe(nil), Parser::AST::Node)

# source://rspock//lib/rspock/ast/test_method_def_transformation.rb#16
RSpock::AST::TestMethodDefTransformation::LINE_NUMBER_STR_AST = T.let(T.unsafe(nil), Parser::AST::Node)

# source://rspock//lib/rspock/ast/test_method_def_transformation.rb#14
RSpock::AST::TestMethodDefTransformation::SPACE_STR_AST = T.let(T.unsafe(nil), Parser::AST::Node)

# source://rspock//lib/rspock/ast/test_method_def_transformation.rb#8
RSpock::AST::TestMethodDefTransformation::TEST_INDEX_AST = T.let(T.unsafe(nil), Parser::AST::Node)

# source://rspock//lib/rspock/ast/test_method_dstr_transformation.rb#6
class RSpock::AST::TestMethodDstrTransformation < ::ASTTransform::AbstractTransformation
  # source://rspock//lib/rspock/ast/test_method_dstr_transformation.rb#17
  def on_dstr(node); end
end

# source://rspock//lib/rspock/ast/test_method_dstr_transformation.rb#10
RSpock::AST::TestMethodDstrTransformation::LINE_NUMBER_AST = T.let(T.unsafe(nil), Parser::AST::Node)

# source://rspock//lib/rspock/ast/test_method_dstr_transformation.rb#15
RSpock::AST::TestMethodDstrTransformation::LINE_NUMBER_STR_AST = T.let(T.unsafe(nil), Parser::AST::Node)

# source://rspock//lib/rspock/ast/test_method_dstr_transformation.rb#13
RSpock::AST::TestMethodDstrTransformation::SPACE_STR_AST = T.let(T.unsafe(nil), Parser::AST::Node)

# source://rspock//lib/rspock/ast/test_method_dstr_transformation.rb#7
RSpock::AST::TestMethodDstrTransformation::TEST_INDEX_AST = T.let(T.unsafe(nil), Parser::AST::Node)

# source://rspock//lib/rspock/ast/test_method_transformation.rb#14
class RSpock::AST::TestMethodTransformation < ::ASTTransform::AbstractTransformation
  # @return [TestMethodTransformation] a new instance of TestMethodTransformation
  #
  # source://rspock//lib/rspock/ast/test_method_transformation.rb#15
  def initialize(block_registry, strict: T.unsafe(nil)); end

  # source://rspock//lib/rspock/ast/test_method_transformation.rb#20
  def run(node); end

  private

  # source://rspock//lib/rspock/ast/test_method_transformation.rb#164
  def build_assert_raises(when_node, raises_node); end

  # --- Build final Ruby AST ---
  #
  # source://rspock//lib/rspock/ast/test_method_transformation.rb#95
  def build_ruby_ast(method_call, method_args, body_node, where, hoisted_setups); end

  # source://rspock//lib/rspock/ast/test_method_transformation.rb#118
  def build_test_body(body_node, hoisted_setups); end

  # source://rspock//lib/rspock/ast/test_method_transformation.rb#198
  def build_where_args(header); end

  # source://rspock//lib/rspock/ast/test_method_transformation.rb#192
  def build_where_data_row(row); end

  # --- Where block helpers ---
  #
  # source://rspock//lib/rspock/ast/test_method_transformation.rb#182
  def build_where_iterator(data_rows); end

  # --- Raises condition helpers ---
  #
  # source://rspock//lib/rspock/ast/test_method_transformation.rb#157
  def find_raises_in_next_then(blocks, current_index); end

  # source://rspock//lib/rspock/ast/test_method_transformation.rb#28
  def transform(rspock_ast); end

  # source://rspock//lib/rspock/ast/test_method_transformation.rb#79
  def transform_expect_block(expect_node); end

  # source://rspock//lib/rspock/ast/test_method_transformation.rb#84
  def transform_statement_or_passthrough(child); end

  # source://rspock//lib/rspock/ast/test_method_transformation.rb#50
  def transform_then_block(then_node, hoisted_setups); end
end

# source://rspock//lib/rspock/ast/node.rb#19
class RSpock::AST::TestNode < ::RSpock::AST::Node
  # source://rspock//lib/rspock/ast/node.rb#23
  def body_node; end

  # source://rspock//lib/rspock/ast/node.rb#22
  def def_node; end

  # source://rspock//lib/rspock/ast/node.rb#24
  def where_node; end
end

# source://rspock//lib/rspock/ast/node.rb#46
class RSpock::AST::ThenNode < ::RSpock::AST::Node; end

# source://rspock//lib/rspock/ast/transformation.rb#13
class RSpock::AST::Transformation < ::ASTTransform::AbstractTransformation
  # @return [Transformation] a new instance of Transformation
  #
  # source://rspock//lib/rspock/ast/transformation.rb#23
  def initialize(block_registry: T.unsafe(nil), strict: T.unsafe(nil)); end

  # source://rspock//lib/rspock/ast/transformation.rb#84
  def on_block(node); end

  # source://rspock//lib/rspock/ast/transformation.rb#50
  def on_casgn(node); end

  # source://rspock//lib/rspock/ast/transformation.rb#36
  def on_class(node); end

  # source://rspock//lib/rspock/ast/transformation.rb#61
  def process_casgn_block(node); end

  # source://rspock//lib/rspock/ast/transformation.rb#78
  def process_rspock(node); end

  # source://rspock//lib/rspock/ast/transformation.rb#95
  def source_map_rescue_wrapper(node); end
end

# source://rspock//lib/rspock/ast/transformation.rb#14
RSpock::AST::Transformation::DEFAULT_BLOCK_REGISTRY = T.let(T.unsafe(nil), Hash)

# source://rspock//lib/rspock/ast/transformation.rb#32
RSpock::AST::Transformation::EXTEND_RSPOCK_DECLARATIVE = T.let(T.unsafe(nil), Parser::AST::Node)

# source://rspock//lib/rspock/ast/node.rb#42
class RSpock::AST::WhenNode < ::RSpock::AST::Node; end

# source://rspock//lib/rspock/ast/node.rb#58
class RSpock::AST::WhereNode < ::RSpock::AST::Node
  # source://rspock//lib/rspock/ast/node.rb#66
  def data_rows; end

  # source://rspock//lib/rspock/ast/node.rb#61
  def header; end
end

# source://rspock//lib/rspock/backtrace_filter.rb#5
class RSpock::BacktraceFilter
  # Constructs a new BacktraceFilter instance.
  #
  # @param source_map_provider [::ASTTransform::SourceMap] The source map provider to be used.
  # @return [BacktraceFilter] a new instance of BacktraceFilter
  #
  # source://rspock//lib/rspock/backtrace_filter.rb#9
  def initialize(source_map_provider: T.unsafe(nil)); end

  # Filters the backtrace of the given +exception+ and applies the filtered backtrace to the exception.
  #
  # @param exception [Exception] The exception to be filtered.
  # @return [void]
  #
  # source://rspock//lib/rspock/backtrace_filter.rb#18
  def filter_exception(exception); end

  # Filters the given location.
  #
  # @param location [String] A location string.
  # @return [String] The filtered location.
  #
  # source://rspock//lib/rspock/backtrace_filter.rb#27
  def filter_string(location); end

  private

  # source://rspock//lib/rspock/backtrace_filter.rb#45
  def location_builder(location); end

  # source://rspock//lib/rspock/backtrace_filter.rb#41
  def source_mapped_backtrace(e); end
end

# source://rspock//lib/rspock/declarative.rb#4
module RSpock::Declarative
  # source://rspock//lib/rspock/declarative.rb#5
  def test(name, &block); end
end

# source://rspock//lib/rspock/helpers/block_capture.rb#4
module RSpock::Helpers; end

# source://rspock//lib/rspock/helpers/block_capture.rb#5
module RSpock::Helpers::BlockCapture
  class << self
    # Installs a block-capture wrapper on +obj+ for +method_name+.
    # Must be called AFTER Mocha's expects/stubs so the wrapper sits
    # in front of whatever Mocha installed.
    #
    # Returns a lambda that, when called, returns the captured block
    # (or nil if no block was passed).
    #
    # source://rspock//lib/rspock/helpers/block_capture.rb#12
    def capture(obj, method_name); end
  end
end

# source://rspock//lib/rspock/version.rb#2
RSpock::VERSION = T.let(T.unsafe(nil), String)
