# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rspock` gem.
# Please instead update this file by running `bin/tapioca gem rspock`.

module RSpock; end
module RSpock::AST; end

class RSpock::AST::Block
  def initialize(type, node); end

  def <<(child_node); end
  def children; end
  def node; end
  def node_container=(value); end
  def node_container?; end
  def range; end
  def succession_error_msg; end
  def successors; end
  def type; end
  def unshift(child_node); end
  def valid_successor?(block); end
end

class RSpock::AST::BlockError < ::StandardError; end

class RSpock::AST::CleanupBlock < ::RSpock::AST::Block
  def initialize(node); end

  def successors; end
end

class RSpock::AST::ComparisonToAssertionTransformation < ::ASTTransform::AbstractTransformation
  def initialize(*ignored_method_call_symbols); end

  def on_send(node); end

  private

  def ignored_method_call_node?(node); end
  def transform_to_assert_equal(node); end
  def transform_to_refute_equal(node); end
end

class RSpock::AST::EndBlock < ::RSpock::AST::Block
  def initialize; end

  def successors; end
end

class RSpock::AST::ExpectBlock < ::RSpock::AST::Block
  def initialize(node); end

  def children; end
  def successors; end
end

class RSpock::AST::GivenBlock < ::RSpock::AST::Block
  def initialize(node); end

  def successors; end
end

class RSpock::AST::HeaderNodesTransformation < ::ASTTransform::AbstractTransformation
  def initialize(header); end

  def on_send(node); end
  def run(node); end

  private

  def header_node?(node); end
end

class RSpock::AST::InteractionTransformation < ::ASTTransform::AbstractTransformation
  def interaction_node?(node); end
  def run(node); end

  private

  def any_matcher_node?(node); end
  def chain_call(receiver_node, method_name, *arg_nodes); end
  def parse_lhs(node); end
  def parse_node(node); end
  def parse_rhs(node); end
  def raise_lhs_error(node, msg_prefix: T.unsafe(nil), msg_suffix: T.unsafe(nil)); end
  def range(node); end
  def transform_erange_node(receiver_node, min_node, max_node); end
  def transform_irange_node(receiver_node, min_node, max_node); end
  def transform_node; end
end

RSpock::AST::InteractionTransformation::ALLOWED_NODES = T.let(T.unsafe(nil), Array)
class RSpock::AST::InteractionTransformation::InteractionError < ::RuntimeError; end

class RSpock::AST::MethodCallToLVarTransformation < ::ASTTransform::AbstractTransformation
  def initialize(*method_symbols); end

  def method_call_node?(node); end
  def on_send(node); end
end

class RSpock::AST::StartBlock < ::RSpock::AST::Block
  def initialize(node); end

  def succession_error_msg; end
  def successors; end
end

RSpock::AST::StartBlock::SUCCESSORS_WITHOUT_CHILDREN = T.let(T.unsafe(nil), Array)
RSpock::AST::StartBlock::SUCCESSORS_WITH_CHILDREN = T.let(T.unsafe(nil), Array)

class RSpock::AST::TestMethodDefTransformation < ::ASTTransform::AbstractTransformation
  def on_dstr(node); end
  def on_str(node); end
  def run(node); end
end

RSpock::AST::TestMethodDefTransformation::LINE_NUMBER_AST = T.let(T.unsafe(nil), Parser::AST::Node)
RSpock::AST::TestMethodDefTransformation::LINE_NUMBER_STR_AST = T.let(T.unsafe(nil), Parser::AST::Node)
RSpock::AST::TestMethodDefTransformation::SPACE_STR_AST = T.let(T.unsafe(nil), Parser::AST::Node)
RSpock::AST::TestMethodDefTransformation::TEST_INDEX_AST = T.let(T.unsafe(nil), Parser::AST::Node)

class RSpock::AST::TestMethodDstrTransformation < ::ASTTransform::AbstractTransformation
  def on_dstr(node); end
end

RSpock::AST::TestMethodDstrTransformation::LINE_NUMBER_AST = T.let(T.unsafe(nil), Parser::AST::Node)
RSpock::AST::TestMethodDstrTransformation::LINE_NUMBER_STR_AST = T.let(T.unsafe(nil), Parser::AST::Node)
RSpock::AST::TestMethodDstrTransformation::SPACE_STR_AST = T.let(T.unsafe(nil), Parser::AST::Node)
RSpock::AST::TestMethodDstrTransformation::TEST_INDEX_AST = T.let(T.unsafe(nil), Parser::AST::Node)

class RSpock::AST::TestMethodTransformation < ::ASTTransform::AbstractTransformation
  def initialize(source_map, start_block_class, end_block_class, strict: T.unsafe(nil)); end

  def run(node); end

  private

  def add_block(block); end
  def build_ast(node); end
  def build_block(node); end
  def build_test_body; end
  def build_test_method_def(node); end
  def build_where_block_args(header); end
  def build_where_block_data_row(row); end
  def build_where_block_data_rows(rows); end
  def build_where_block_iterator(rows); end
  def cleanup_block; end
  def current_scope; end
  def first_scope; end
  def parse(node); end
  def parse_node(node); end
  def test_method_nodes(node); end
  def then_block; end
  def when_block; end
  def where_block; end
end

class RSpock::AST::ThenBlock < ::RSpock::AST::Block
  def initialize(node); end

  def children; end
  def interactions; end
  def successors; end

  private

  def interaction_transformation; end
end

class RSpock::AST::Transformation < ::ASTTransform::AbstractTransformation
  def initialize(start_block_class: T.unsafe(nil), end_block_class: T.unsafe(nil), source_map: T.unsafe(nil), strict: T.unsafe(nil)); end

  def on_block(node); end
  def on_casgn(node); end
  def on_class(node); end
  def process_casgn_block(node); end
  def process_rspock(node); end
  def source_map_rescue_wrapper(node); end
end

RSpock::AST::Transformation::DefaultSourceMap = T.let(T.unsafe(nil), Hash)
RSpock::AST::Transformation::EXTEND_RSPOCK_DECLARATIVE = T.let(T.unsafe(nil), Parser::AST::Node)

class RSpock::AST::WhenBlock < ::RSpock::AST::Block
  def initialize(node); end

  def successors; end
end

class RSpock::AST::WhereBlock < ::RSpock::AST::Block
  def initialize(node); end

  def data; end
  def header; end
  def successors; end

  private

  def data_pipe_node?(node, data); end
  def header_pipe_node?(node, header); end
  def parse_data; end
  def parse_header; end
  def terminal_data_node?(node, data); end
  def terminal_header_node?(node, header); end
end

class RSpock::AST::WhereBlock::MalformedError < ::StandardError; end

class RSpock::BacktraceFilter
  def initialize(source_map_provider: T.unsafe(nil)); end

  def filter_exception(exception); end
  def filter_string(location); end

  private

  def location_builder(location); end
  def source_mapped_backtrace(e); end
end

module RSpock::Declarative
  def test(name, &block); end
end

RSpock::VERSION = T.let(T.unsafe(nil), String)
