# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `simplecov-sorbet` gem.
# Please instead update this file by running `bin/tapioca gem simplecov-sorbet`.


# source://simplecov-sorbet//lib/simplecov/sorbet/version.rb#4
module SimpleCov; end

class SimpleCov::Directive
  extend ::SimpleCov::Sorbet::DirectiveExtension
end

# SimpleCov extension for Sorbet codebases: skips type-level Sorbet constructs coverage should not measure —
# multi-line +T.type_alias+ blocks, +sig+ blocks, and +T.absurd+ sends. Requiring this file installs the
# extension; Module#prepend is idempotent, so requiring it more than once is harmless.
#
# source://simplecov-sorbet//lib/simplecov/sorbet/version.rb#5
module SimpleCov::Sorbet; end

# Prepended onto SimpleCov::Directive's singleton class. Directive.disabled_ranges is the one choke point both
# SourceFile (loaded files) and LinesClassifier (tracked-but-unloaded files) consult for skip ranges, so
# extending its result covers every path SimpleCov classifies lines through. Ignored ranges join all three
# categories: type-level constructs are not behavior, so any line, branch, or method inside them is skippable.
#
# source://simplecov-sorbet//lib/simplecov/sorbet/directive_extension.rb#10
module SimpleCov::Sorbet::DirectiveExtension
  # source://simplecov-sorbet//lib/simplecov/sorbet/directive_extension.rb#14
  sig { params(src_lines: T::Array[::String]).returns(T::Hash[::Symbol, T::Array[T::Range[::Integer]]]) }
  def disabled_ranges(src_lines); end

  private

  # Scans +source+ for type-level Sorbet constructs (see IgnoredRanges). Unparseable source yields no ranges:
  # coverage annotation must never take down a suite's reporting, and a file Ruby executed but this parser
  # rejects has no constructs we could trust anyway. The rescue is deliberately wide — Prism parses most broken
  # source tolerantly, and what escapes is not Parser::SyntaxError but arbitrary errors from the whitequark
  # builder choking on error-recovered trees (e.g. NoMethodError in join_exprs).
  #
  # source://simplecov-sorbet//lib/simplecov/sorbet/directive_extension.rb#35
  sig { params(source: ::String).returns(T::Array[T::Range[::Integer]]) }
  def ignored_ranges(source); end

  # The parser is fixed for the extension's lifetime. Prepended onto SimpleCov::Directive's singleton class,
  # this module has no constructor to own it, so the singleton's ivar plays that role.
  #
  # source://simplecov-sorbet//lib/simplecov/sorbet/directive_extension.rb#46
  sig { returns(::ASTTransform::SourceParser) }
  def source_parser; end
end

# Read-only analysis pass collecting the line ranges of type-level Sorbet constructs coverage should ignore.
# Detection is purely syntactic — this gem never loads Sorbet's type system. Three constructs are collected:
#
# - +T.type_alias+ blocks: sorbet-runtime resolves aliases lazily and collection checks are shallow, so a
#   multi-line alias body never executes and reads as a permanent coverage miss.
# - +sig+ blocks (bare or with a receiver, e.g. +T::Sig::WithoutRuntime.sig+): sigs are type metadata whose
#   correctness +srb tc+ owns; coverage should measure behavior. Only multi-line blocks are collected — a
#   single-line +sig { ... }+ occupies the send's own line, which executes at load.
# - +T.absurd+ sends: unreachable by definition when exhaustiveness holds, so in correct code the line is a
#   permanent coverage miss.
#
# source://simplecov-sorbet//lib/simplecov/sorbet/ignored_ranges.rb#16
class SimpleCov::Sorbet::IgnoredRanges < ::ASTTransform::AbstractAnalysis
  # source://simplecov-sorbet//lib/simplecov/sorbet/ignored_ranges.rb#34
  sig { void }
  def initialize; end

  # Collects the block's full expression range when the block's send is a +T.type_alias+ or a multi-line +sig+.
  #
  # source://simplecov-sorbet//lib/simplecov/sorbet/ignored_ranges.rb#58
  sig { params(node: ::Parser::AST::Node).returns(::Parser::AST::Node) }
  def on_block(node); end

  # Collects the send's full expression range when it is a +T.absurd+ call.
  #
  # source://simplecov-sorbet//lib/simplecov/sorbet/ignored_ranges.rb#45
  sig { params(node: ::Parser::AST::Node).returns(::Parser::AST::Node) }
  def on_send(node); end

  # One line range per ignored construct, in source order.
  #
  # source://simplecov-sorbet//lib/simplecov/sorbet/ignored_ranges.rb#31
  sig { returns(T::Array[T::Range[::Integer]]) }
  def ranges; end

  private

  # source://simplecov-sorbet//lib/simplecov/sorbet/ignored_ranges.rb#80
  sig { params(node: ::Parser::AST::Node).returns(T::Range[::Integer]) }
  def line_range(node); end
end

# Structural patterns for the +T+ receiver (node equality ignores source locations): +T+ and its explicit
# top-level form +::T+.
#
# source://simplecov-sorbet//lib/simplecov/sorbet/ignored_ranges.rb#21
SimpleCov::Sorbet::IgnoredRanges::T_RECEIVERS = T.let(T.unsafe(nil), Array)

# source://simplecov-sorbet//lib/simplecov/sorbet/version.rb#6
SimpleCov::Sorbet::VERSION = T.let(T.unsafe(nil), String)
