name: dev
ruby: "4.0.1"
commands:
  up:
    desc: Setup dev environment (install bundler from dependencies.rb, bundle install)
    run: ./bin/setup.rb
  rbi:
    desc: Regenerate gem RBI files (run after changing Gemfile)
    run: ./bin/rbi.rb
  tc:
    desc: Type check (verify gem RBIs are in sync, then srb tc)
    run: ./bin/tc.rb
  test:
    desc: Run this repo's tests
    run: ./bin/test.rb
  release:
    desc: Release a new version (bump, tag, push, Homebrew formula)
    run: ./bin/release.rb
  console:
    desc: Start Ruby console
    run: ./bin/console
    repl: true
