name: dev

commands:
  up:
    desc: Setup dev environment (install bundler from dependencies.rb, bundle install)
    run: ./bin/setup.rb
  test:
    desc: Run this repo's tests
    run: ./bin/test.rb
  console:
    desc: Start Ruby console with dev code loaded (pry)
    run: ./bin/console
  c:
    desc: Alias for console
    run: dev console
