# typed: strict
# frozen_string_literal: true

require "fileutils"
require "pathname"

module Dev
  module Learnings
    # Renders the org invariants index once, cache-side, as a generated
    # always-on Cursor rule, and links each project's
    # .cursor/rules/org-invariants.mdc at that render as a symlink.
    #
    # Carriage without commits: the canonical lines live only in the knowledge
    # repo's index.md ("## Invariants (always-on)" section). The render lands
    # in one machine-local file beside the cache, so one refresh updates every
    # project on the machine simultaneously; a project's footprint is a single
    # symlink (same shape as the user-global skill links). The render is
    # content-compared, and the project link only ever replaces a symlink or a
    # file carrying the generated marker, so a user file in the way survives
    # untouched.
    #
    # The section extraction is also the Tier-0 prompt seam: prompt_block is
    # what `dev learnings invariants` prints for consumers (e.g. ai-flow) that
    # embed the invariants in a prompt instead of a rules file.
    #
    # Stateless: one reusable instance renders any index into any target.
    class InvariantsRenderer
      extend T::Sig

      # The heading the invariant lines live under in the knowledge index,
      # and where the next section cuts them off.
      INVARIANTS_HEADING = /^## Invariants\b/
      SECTION_HEADING = /^## /

      GENERATED_MARKER = "<!-- generated by dev learnings sync — do not edit or commit;"

      # Pre-rename renders carried this marker; the link step recognizes it so
      # upgrading replaces the old per-project file with a symlink.
      LEGACY_GENERATED_MARKER = "<!-- generated by dev knowledge sync — do not edit or commit;"

      # Trails the invariant lines in every rendered/printed block: the lines
      # only buy awareness, the pointed skills carry the rules.
      SKILL_POINTER_NOTE =
        "Each → pointer is an on-demand skill installed under ~/.cursor/skills/ —\n" \
          "read it before working in that entry's territory."

      # The Tier-0 prompt block: the invariants section extracted from the org
      # index, plus the skill-pointer note — embeddable in a prompt as-is.
      #
      # @param index_file [Pathname] the cached knowledge index (index.md)
      # @return [String, nil] nil when the index (or the section) doesn't exist
      sig { params(index_file: Pathname).returns(T.nilable(String)) }
      def prompt_block(index_file)
        lines = invariant_lines(index_file)
        return nil if lines.nil?

        "#{lines}\n\n#{SKILL_POINTER_NOTE}"
      end

      # Render (or refresh, or retract) the machine-side generated rule.
      #
      # @param index_file [Pathname] the cached knowledge index (index.md)
      # @param rendered_file [Pathname] the machine-local render target
      #   (beside the cache; never inside a project)
      # @param repo [String] knowledge repo label for the generated header
      # @return [void]
      sig { params(index_file: Pathname, rendered_file: Pathname, repo: String).void }
      def render(index_file:, rendered_file:, repo:)
        block = prompt_block(index_file)
        if block.nil?
          FileUtils.rm_f(rendered_file)
          return
        end

        content = rule_content(block, repo)
        return if rendered_file.file? && rendered_file.read == content

        FileUtils.mkdir_p(rendered_file.dirname)
        rendered_file.write(content)
      end

      # Link a project's rules file at the machine-side render (or retract the
      # link when the render is gone). Symlinks and marker-carrying generated
      # files are ours to manage; anything else is user-owned — warn and leave.
      #
      # @param rendered_file [Pathname] the machine-local render
      # @param rules_file [Pathname] the target .mdc inside a project
      # @return [void]
      sig { params(rendered_file: Pathname, rules_file: Pathname).void }
      def link(rendered_file:, rules_file:)
        return unlink(rules_file) unless rendered_file.file?
        return if rules_file.symlink? && rules_file.readlink == rendered_file
        return warn_user_owned(rules_file) if user_owned?(rules_file)

        FileUtils.mkdir_p(rules_file.dirname)
        FileUtils.rm_f(rules_file)
        File.symlink(rendered_file, rules_file)
      end

      private

      # The invariants section body, or nil when the index (or the section)
      # doesn't exist — nil means the render target must be retracted, which
      # is a normal state of the world, not an error.
      #
      # @param index_file [Pathname]
      # @return [String, nil]
      sig { params(index_file: Pathname).returns(T.nilable(String)) }
      def invariant_lines(index_file)
        return nil unless index_file.file?

        section = T.let([], T::Array[String])
        in_section = T.let(false, T::Boolean)
        index_file.read.each_line do |line|
          if line.match?(INVARIANTS_HEADING)
            in_section = true
          elsif in_section && line.match?(SECTION_HEADING)
            break
          elsif in_section
            section << line
          end
        end
        return nil unless in_section

        section.join.strip
      end

      # @param block [String] the Tier-0 prompt block
      # @param repo [String]
      # @return [String] the full .mdc content
      sig { params(block: String, repo: String).returns(String) }
      def rule_content(block, repo)
        <<~CONTENT
          ---
          description: "Org engineering invariants — always-on index, generated by dev from #{repo}"
          alwaysApply: true
          ---
          #{GENERATED_MARKER} changes land in #{repo} -->

          # Org invariants

          #{block}
        CONTENT
      end

      # A regular file at the link target that doesn't carry a generated
      # marker was written by the user, not by dev.
      #
      # @param rules_file [Pathname]
      # @return [Boolean]
      sig { params(rules_file: Pathname).returns(T::Boolean) }
      def user_owned?(rules_file)
        return false if rules_file.symlink? || !rules_file.file?

        existing = rules_file.read
        !existing.include?(GENERATED_MARKER) && !existing.include?(LEGACY_GENERATED_MARKER)
      end

      # Remove a link (or a previously generated file) whose render is gone.
      #
      # @param rules_file [Pathname]
      # @return [void]
      sig { params(rules_file: Pathname).void }
      def unlink(rules_file)
        return unless rules_file.symlink? || rules_file.file?
        return warn_user_owned(rules_file) if user_owned?(rules_file)

        FileUtils.rm_f(rules_file)
      end

      # @param rules_file [Pathname]
      # @return [void]
      sig { params(rules_file: Pathname).void }
      def warn_user_owned(rules_file)
        $stderr.puts "dev: warning: #{rules_file} exists and is not dev-generated — leaving it in place."
      end
    end
  end
end
