# frozen_string_literal: true

require "fileutils"
require "pathname"

module Dev
  module Knowledge
    # Renders the org invariants index into a project's rules dir as a
    # generated, always-on Cursor rule (.cursor/rules/org-invariants.mdc).
    #
    # Carriage without commits: the canonical lines live only in the knowledge
    # repo's index.md ("## Invariants (always-on)" section); this render is
    # regenerated from the machine cache at every hook point, so drift is
    # structurally impossible — no copies, no stamps, no fan-out PRs. The
    # write is content-compared and only ever touches a file carrying the
    # generated marker, so a user file in the way survives untouched.
    #
    # Stateless: one reusable instance renders any index into any target.
    class InvariantsRenderer
      # The heading the invariant lines live under in the knowledge index,
      # and where the next section cuts them off.
      INVARIANTS_HEADING = /^## Invariants\b/
      SECTION_HEADING = /^## /

      GENERATED_MARKER = "<!-- generated by dev knowledge sync — do not edit or commit;"

      # Render (or refresh, or retract) the generated rule.
      #
      # @param index_file [Pathname] the cached knowledge index (index.md)
      # @param rules_file [Pathname] the target .mdc inside a project
      # @param repo [String] knowledge repo label for the generated header
      # @return [void]
      def render(index_file:, rules_file:, repo:)
        lines = invariant_lines(index_file)
        return retract(rules_file) if lines.nil?

        write_if_changed(rules_file, rule_content(lines, repo))
      end

      private

      # The invariants section body, or nil when the index (or the section)
      # doesn't exist — nil means the render target must be retracted, which
      # is a normal state of the world, not an error.
      #
      # @param index_file [Pathname]
      # @return [String, nil]
      def invariant_lines(index_file)
        return nil unless index_file.file?

        section = []
        in_section = false
        index_file.read.each_line do |line|
          if line.match?(INVARIANTS_HEADING)
            in_section = true
          elsif in_section && line.match?(SECTION_HEADING)
            break
          elsif in_section
            section << line
          end
        end
        return nil unless in_section

        section.join.strip
      end

      # @param lines [String] the invariant index lines
      # @param repo [String]
      # @return [String] the full .mdc content
      def rule_content(lines, repo)
        <<~CONTENT
          ---
          description: "Org engineering invariants — always-on index, generated by dev from #{repo}"
          alwaysApply: true
          ---
          #{GENERATED_MARKER} changes land in #{repo} -->

          # Org invariants

          #{lines}

          Each → pointer is an on-demand skill installed under ~/.cursor/skills/ —
          read it before working in that entry's territory.
        CONTENT
      end

      # Write the rule unless it is already current. A pre-existing file
      # without the generated marker is user-owned: warn and leave it.
      #
      # @param rules_file [Pathname]
      # @param content [String]
      # @return [void]
      def write_if_changed(rules_file, content)
        if rules_file.file?
          existing = rules_file.read
          return if existing == content
          return warn_user_owned(rules_file) unless existing.include?(GENERATED_MARKER)
        end

        FileUtils.mkdir_p(rules_file.dirname)
        rules_file.write(content)
      end

      # Remove a previously generated rule whose source is gone. Only a file
      # carrying the marker is ever deleted.
      #
      # @param rules_file [Pathname]
      # @return [void]
      def retract(rules_file)
        return unless rules_file.file?
        return warn_user_owned(rules_file) unless rules_file.read.include?(GENERATED_MARKER)

        rules_file.delete
      end

      # @param rules_file [Pathname]
      # @return [void]
      def warn_user_owned(rules_file)
        $stderr.puts "dev: warning: #{rules_file} exists and is not dev-generated — leaving it in place."
      end
    end
  end
end
